spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/student_club?characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    #关闭thymeleaf的缓存，可以让页面实时刷新
    cache: false
    encoding: UTF-8
  config:
    name: application # Config file name.
  # HTTP encoding (HttpEncodingProperties)
  http:
    encoding:
      charset: UTF-8
      enabled: true
mybatis:
  type-aliases-package: com.na.design.bean
logging:
  config: classpath:logback-spring.xml
server:
  port: 8080
  error:
    path: /error # Path of the error controller.
  servlet:
    path: /
  tomcat:
    accesslog:
      enabled: false
# EMBEDDED SERVER CONFIGURATION (ServerProperties)

